# Common load balancer service for CNS Manager
apiVersion: v1
kind: Service
metadata:
  name: cns-manager
  labels:
    app: cns-manager
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: prometheus
      port: 2114
      protocol: TCP
      targetPort: 2114
  selector:
    app: cns-manager
  sessionAffinity: None
